services:
  # Web Service (Laravel App)
  - type: web
    name: school-cbt-system
    runtime: docker  # or "php" if you prefer not using Docker
    region: frankfurt
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    disk:
      name: storage
      mountPath: /var/www/html/storage
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        value: base64:lzWyASlzFThizz1WFnnF5CmGtVStiCF/oBo3WUQjQQE=
      - key: APP_URL
        value: https://school-cbt-system.onrender.com
      - key: DB_CONNECTION
        value: pgsql       # PostgreSQL on Render
      - key: DB_HOST
        value: dpg-d6fvvic50q8c7382edu0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: cbt_db_ciw1
      - key: DB_USERNAME
        value: cbt_db_ciw1_user
      - key: DB_PASSWORD
        value: hvs5jSoNCXbooKYAD5Id0iWJ4sBu9wRg